[package]
name = "glama"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.1", features = ["derive"] }
pyo3 = { version = "*", features = ["abi3-py37", "extension-module"] }